#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAE2536227F69F181 (hs@ox.cx)
#
Name     : argon2_cffi
Version  : 19.2.0
Release  : 6
URL      : https://files.pythonhosted.org/packages/e4/96/f1bf2369f29794971f836b8eff5e3bdb653043f1b61d104eae21b1de3ccb/argon2-cffi-19.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e4/96/f1bf2369f29794971f836b8eff5e3bdb653043f1b61d104eae21b1de3ccb/argon2-cffi-19.2.0.tar.gz
Source1 : https://files.pythonhosted.org/packages/e4/96/f1bf2369f29794971f836b8eff5e3bdb653043f1b61d104eae21b1de3ccb/argon2-cffi-19.2.0.tar.gz.asc
Summary  : The secure Argon2 password hashing algorithm.
Group    : Development/Tools
License  : CC0-1.0 MIT
Requires: argon2_cffi-license = %{version}-%{release}
Requires: argon2_cffi-python = %{version}-%{release}
Requires: argon2_cffi-python3 = %{version}-%{release}
Requires: cffi
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : util-linux
BuildRequires : virtualenv

%description
# Argon2
[![Build Status](https://travis-ci.org/P-H-C/phc-winner-argon2.svg?branch=master)](https://travis-ci.org/P-H-C/phc-winner-argon2)
[![Build status](https://ci.appveyor.com/api/projects/status/8nfwuwq55sgfkele?svg=true)](https://ci.appveyor.com/project/P-H-C/phc-winner-argon2)
[![codecov.io](https://codecov.io/github/P-H-C/phc-winner-argon2/coverage.svg?branch=master)](https://codecov.io/github/P-H-C/phc-winner-argon2?branch=master)

%package license
Summary: license components for the argon2_cffi package.
Group: Default

%description license
license components for the argon2_cffi package.


%package python
Summary: python components for the argon2_cffi package.
Group: Default
Requires: argon2_cffi-python3 = %{version}-%{release}

%description python
python components for the argon2_cffi package.


%package python3
Summary: python3 components for the argon2_cffi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the argon2_cffi package.


%prep
%setup -q -n argon2-cffi-19.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572273087
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/argon2_cffi
cp %{_builddir}/argon2-cffi-19.2.0/LICENSE %{buildroot}/usr/share/package-licenses/argon2_cffi/00ff890e8493d10b07d5d3fafa23639bb071e443
cp %{_builddir}/argon2-cffi-19.2.0/extras/libargon2/LICENSE %{buildroot}/usr/share/package-licenses/argon2_cffi/edffb32348c3b38dd68cfb2e6cac9dc4a3502c8b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/argon2_cffi/00ff890e8493d10b07d5d3fafa23639bb071e443
/usr/share/package-licenses/argon2_cffi/edffb32348c3b38dd68cfb2e6cac9dc4a3502c8b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
